import {
  BadgeEuro,
  Blocks,
  BookOpen,
  Bot,
  Boxes,
  FileDigit,
  FileText,
  FolderKanban,
  LayoutDashboard,
  Package,
  Settings2,
  ShieldCheck,
  Truck,
  Users,
  Waypoints,
  Activity,
  type LucideIcon,
} from "lucide-react";

export type AdminNavSection = "stable" | "pipeline";

export type AdminNavItem = {
  title: string;
  href: string;
  description: string;
  icon: LucideIcon;
  enabled: boolean;
  section: AdminNavSection;
  badge?: string;
};

export const adminNavItems: AdminNavItem[] = [
  {
    title: "Genel Bakış",
    href: "/admin",
    description: "Genel durum ve sistem sağlığı",
    icon: LayoutDashboard,
    enabled: true,
    section: "stable",
  },
  {
    title: "Sayfalar",
    href: "/admin/pages",
    description: "Public sayfalar ve locale içerik yönetimi",
    icon: FileText,
    enabled: true,
    section: "stable",
  },
  {
    title: "Blog",
    href: "/admin/blog",
    description: "Editoryal içerik ve yayın hazırlığı",
    icon: BookOpen,
    enabled: true,
    section: "stable",
  },
  {
    title: "Medya",
    href: "/admin/media",
    description: "Gerçek medya referansları ve etiket yüzeyi",
    icon: FolderKanban,
    enabled: true,
    section: "stable",
  },
  {
    title: "SEO & Ayarlar",
    href: "/admin/settings",
    description: "SEO kapsaması ve runtime governance görünürlüğü",
    icon: Settings2,
    enabled: true,
    section: "stable",
    badge: "Yeni",
  },
  {
    title: "Araç Modelleri",
    href: "/admin/models",
    description: "Şasi, ağırlık ve temel ölçüler",
    icon: Truck,
    enabled: true,
    section: "stable",
  },
  {
    title: "Kategoriler",
    href: "/admin/categories",
    description: "Ürün sınıflandırma omurgası",
    icon: Blocks,
    enabled: true,
    section: "stable",
  },
  {
    title: "Ürünler",
    href: "/admin/products",
    description: "Parça ve donanım havuzu",
    icon: Package,
    enabled: true,
    section: "stable",
  },
  {
    title: "Paketler",
    href: "/admin/packages",
    description: "Hazır konfigürasyon setleri",
    icon: Boxes,
    enabled: true,
    section: "stable",
  },
  {
    title: "Build Versions",
    href: "/admin/build-versions",
    description: "Build ve versiyon bağı omurgası",
    icon: Waypoints,
    enabled: true,
    section: "stable",
    badge: "Yeni",
  },
  {
    title: "Lead'ler",
    href: "/admin/leads",
    description: "Müşteri adayı operasyon hattı",
    icon: Users,
    enabled: true,
    section: "stable",
    badge: "CRM",
  },
  {
    title: "Offers",
    href: "/admin/offers",
    description: "Teklif operasyonu ve satış geçişi",
    icon: BadgeEuro,
    enabled: true,
    section: "stable",
    badge: "CRM",
  },
  {
    title: "Siparişler",
    href: "/admin/orders",
    description: "Üretim akışı ve teslim operasyonu",
    icon: Activity,
    enabled: true,
    section: "stable",
    badge: "CRM",
  },
  {
    title: "Kural Motoru",
    href: "/admin/rules",
    description: "Teknik uyumluluk ve blokaj mantığı",
    icon: Settings2,
    enabled: true,
    section: "stable",
  },
  {
    title: "AI Core",
    href: "/admin/ai-core",
    description: "Governance ve knowledge readiness görünürlüğü",
    icon: Bot,
    enabled: true,
    section: "stable",
  },
  {
    title: "Audit & Publish",
    href: "/admin/audit",
    description: "Audit logları ve publish revision görünürlüğü",
    icon: ShieldCheck,
    enabled: true,
    section: "stable",
    badge: "Yeni",
  },
  {
    title: "Kullanıcılar",
    href: "/admin/users",
    description: "Mevcut kullanıcı ve rol yönetimi çekirdeği",
    icon: Users,
    enabled: true,
    section: "stable",
    badge: "Core",
  },
  {
    title: "Datasheet Merkezi",
    href: "/admin/datasheets",
    description: "AI bilgi tabanı belge kayıt merkezi",
    icon: FileDigit,
    enabled: true,
    section: "stable",
    badge: "Yeni",
  },
];
